config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get 'users/poster', to: 'users#poster', as: 'poster'
  get 'users/hasher', to: 'users#hasher', as: 'hasher'
  post 'users/reply_to', to: 'users#reply_to', as: 'reply'
  get 'users/retweet', to: 'users#retweet', as: 'retweet'
  get 'users/unretweet', to: 'users#unretweet', as: 'unretweet'
  get 'users/favorite', to: 'users#favorite', as: 'favorite'
  get 'users/unfavorite', to: 'users#unfavorite', as: 'unfavorite'
  get 'users/follow', to: 'users#follow', as: 'follow'
  get 'users/unfollow', to: 'users#unfollow', as: 'unfollow'
  get 'stop', to: 'users#stop', as: 'stop'

  get 'us', to: 'data#us', as: 'us'
  get 'tweetdata', to: 'data#tweet_data', as: 'tweetdata'
  get 'geographytweets', to: 'data#geography_tweets', as: 'geographytweets'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    # Check if user exists already, if not create one
    where(auth.slice('provider', 'uid', 'oauth_token', 'oauth_token_secret')).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.name = auth['info']['nickname']
      user.token = auth['credentials']['token']
      user.token_secret = auth['credentials']['secret']
    end
  end
end

app/controllers/users_controller.rb
include ApplicationHelper
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :index, :poster, :hasher,
    :favorite, :unfavorite, :reply_to, :retweet, :unretweet, :follow, :unfollow]

    # todo: If we are going to be repeating twitter_config, we should make it a 
    # before method and delegate to specific actions
    # twitter_config global helper establishes OAuth connection

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    #@token = @current.token
    #@secret = @current.token_secret
  end

  # todo: clean up hasher method by extracting to model
  def hasher
    # capture hash parameter from form_tag
    @search_term = params[:search_term]
    # @search_term[0] = ''
    # Open stream with searchable term
    #todo: Reopen stream
    open_stream(@search_term)

    # todo: Implement Frequency Bubbles
    $frequencyHash = {}

    # twitter_config global helper establishes OAuth connection
    client = twitter_config(@current)
    hashtag = "#" + @search_term
    @tweets = client.search(hashtag).take(250)
    @tweets.each do |t|
      frequencyOfValVars(t.attrs[:text])
    end
    @cleanHash = $frequencyHash.sort_by {|k, v| v}.reverse

    # Get the top 50 tweets based on follower count
    topFollowedTweets = @tweets.sort_by {|t| t.attrs[:user][:followers_count]}.reverse[0..50]
    # Removes duplicates based on name and extract only 9
    @topFollowed = topFollowedTweets.uniq {|t| t.attrs[:user][:screen_name] }[0..8]
    #friends = my_friends    #(@top9) eventually you'll pass in top9 to identify if following those users

    # topFavorited Tweets
    # topFavoritedTweets = @tweets.sort_by {|t| t.attrs[:favorite_count]}.reverse[0..50]
    # @topFavorited = topFavoritedTweets.uniq{|t| t.attrs[:user][:screen_name] }[0..8]

  end

  def favorite
    client = twitter_config(@current)
    client.favorite!(params[:tweet_id])
  end

  def unfavorite
    client = twitter_config(@current)
    client.unfavorite(params[:tweet_id])
  end

  def reply_to
    client = twitter_config(@current)
    client.update(params[:reply_text], in_reply_to_status_id: params[:reply_to_id])
    redirect_to '', notice: "Reply Worked"
  end

  def retweet
    client = twitter_config(@current)
    client.retweet!(params[:tweet_id])
  end

  def unretweet

  end

  def follow
    client = twitter_config(@current)
    client.follow!(params[:screen_name])
  end

  def unfollow
    client = twitter_config(@current)
    client.unfollow(params[:screen_name])
  end

  def stop
    # This inserts the killer tweet that stops the rake task
    Tweet.create(text: "You have stopped the live stream", stop_feed: "yes")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @current = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end

    def open_stream(search_term)

      # Kill all tweets so we can start with a fresh stream into postgreSQL:
      Tweet.destroy_all
      @tweets = Tweet.all

      # This is the command that starts the rake task save_tweets in lib/tasks/save_tweets
      system "rake save_tweets SEARCH_TERM=#{search_term} USER_ID=#{session[:user_id]} &"
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/hasher.html.erb
<div id="hasherWrapper">
	<%= link_to 'Stop Stream', stop_path, remote: true %>

	<section class="tweetMap">
		<h2 class="title">Tweet Map</h2>
		<div id="map"></div>
		<p class="flashingTweetText"></p>
	</section>


	<br>
	<br>
	<br>
	<br>
	<br>

	<% if notice %>
	  <p class="notice"><%= notice %></p>
	<% end %>
	
	
	
	<!-- <h2>Temporary Clean Hash</h2> -->
	<%# @cleanHash.each do |k,v| %>
		<!-- <p><%#= k %> - <%#= v %> </p> -->
	<%# end %>
	
	
	<section class="mostValuableTweets">
		<h2 class="title">Top Tweets</h2>
		<% i=1 %>
		<% @topFollowed.each do |t| %>
			<div class="tweet flip">
				<div class="topTweetWrapper">
					<div class="tweetBody overlayBody" style="background-color:#<%=t.attrs[:user][:profile_background_color]%>">
						<h2 class="confirmation">Reply Sent</h2>
						<h3 class="username">@<%= t.attrs[:user][:screen_name] %></h3>
					</div>
					<div class="tweetBody mainBody">
						<div class="contentWrapper">
							<div class="author">
								<div class="userIdentifier">
									<img src="<%=t.attrs[:user][:profile_image_url]%>" alt="" class="avatar">
									<div class="name"><%= t.attrs[:user][:name] %></div>
									<div class="username">@<%= t.attrs[:user][:screen_name] %></div>
								</div>
								<% if t.attrs[:user][:following] %>
									<div class="fol status">
										<a class="followStatus following"><%= image_tag("bird_gray_16.png", height: '16', width: '16', class: 'inlb')%>Following</a>
										<a class="followStatus unfollow btn" data-remote="true" href="unfollow?screen_name=<%=t.attrs[:user][:screen_name]%>">Unfollow</a>
										<a class="followStatus notFollowing" data-remote="true" href="follow?screen_name=<%=t.attrs[:user][:screen_name]%>"><%= image_tag("bird_blue_16.png", height: '16', width: '16', class: 'inlb')%>Follow</a>
										<a class="followStatus follow btn" data-remote="true" href="follow?screen_name=<%=t.attrs[:user][:screen_name]%>">Follow</a>
									</div>
								<% else %>	
									<div class="noFol status">
										<a class="followStatus notFollowing" data-remote="true" href="follow?screen_name=<%=t.attrs[:user][:screen_name]%>"><%= image_tag("bird_blue_16.png", height: '16', width: '16', class: 'inlb')%>Follow</a>
										<a class="followStatus follow btn" data-remote="true" href="follow?screen_name=<%=t.attrs[:user][:screen_name]%>">Follow</a>
										<a class="followStatus following" data-remote="true"><%= image_tag("bird_gray_16.png", height: '16', width: '16', class: 'inlb')%>Following</a>
										<a class="followStatus unfollow btn" data-remote="true" href="unfollow?screen_name=<%=t.attrs[:user][:screen_name]%>">Unfollow</a>
									</div>
								<% end %>
							</div>
							<div class="tweetText"><%= t.attrs[:text] %></div>
							<div class="metaFooter">
								<div class="tweetTimestamp"><a href="<%# permalink%>"><%= Date.parse(t.attrs[:created_at]).to_formatted_s(:long) %></a></div> <!-- Must always be linked to tweet Permalink -->
								<div class="tweetActions">
									<% if t.attrs[:retweeted] %>
										<div class="rt">
											<a class="retweet sent"></a>
										</div>
									<% else %>
										<div class="noRt">
											<a class="retweet sent" data-remote="true"></a>
											<a class="retweet notSent" data-remote="true" href="users/retweet?id=<%=t.attrs[:id]%>"></a>	
										</div>
									<% end %>

									<a class="reply sent"></a>
									<a class="reply notSent" href=""></a>

									<% if t.attrs[:favorited] %>
										<div class="fav">
											<a class="favorite sent" data-remote="true" href="/users/unfavorite?tweet_id=<%#=t.attrs[:id]%>"></a>
											<a class="favorite notSent" data-remote="true" href="/users/favorite?tweet_id=<%#=t.attrs[:id]%>"></a>
										</div>
									<% else %>
										<div class="noFav">
											 <a class="favorite notSent" data-remote="true" href="/users/favorite?tweet_id=<%=t.attrs[:id]%>"></a>
											<a class="favorite sent" data-remote="true" href="/users/unfavorite?tweet_id=<%#=t.attrs[:id]%>"></a>
										</div> 
									<% end %>
								</div>
							</div>
						</div>
						<div class="followerCount"><%= number_with_delimiter(t.attrs[:user][:followers_count])%> Followers</div>
					</div>
					<div class="tweetBody replyBody">
						<div class="replyWrapper">
							<%= form_tag ({controller: 'users', action: 'reply_to'}), remote: true do %>
								<%= text_area_tag(:reply_text, "@#{t.attrs[:user][:screen_name]} ", {class: 'replyText', maxlength: 140}) %><br />
								<%= hidden_field_tag(:reply_to_id, t.attrs[:id]) %>
								<div class="sendReplyWrapper">
									<%= submit_tag('Send Tweet', class: 'sendReply') %>
								</div>
								<div class="letterCount"></div>
							<% end %>
							<a class="flipBack" data-remote="true"></a>
						</div>
					</div>
					<div class="tweetBody userBody">
						<div class="profileBackground">
							<img src=<%= t.attrs[:user][:profile_background_image_url]%>>
						</div>
						<div class="userWrapper">	
							<img src="<%=t.attrs[:user][:profile_image_url]%>" alt="profile image" class="avatar">
							<div class="author">
								<a href="http://twitter.com/<%=t.attrs[:user][:screen_name] %>" class="username">@<%=t.attrs[:user][:screen_name] %></a>
							</div>
							<p class="userInfo"><%= t.attrs[:user][:description]%></p>
							<div class="metaFooter">
								<div class="location"><%= t.attrs[:user][:location] %> </div>
							</div>
							<a class="flipBack" data-remote="true"></a>
							<!-- <div class="flipBack">x</div> -->
												</div>
						</div>
				</div>
			</div>
		<% i += 1 %>
		<% end %>
	</section>
	
	
	<section id="streamingVelocity"></section>


	<!-- <h2>Amount of Tweets</h2>
	<%#= @tweets.count %>
	
	<h1>Hasher Metrics</h1>
	<%# @tweets.each do |t| %>
		<h3>Attempt at parsing data</h3>
		<br>
		<p>All attrs no yaml ['attrs']</p>
		<%#= t.attrs %>
		<br>
		<p>All attrs to_json ['attrs']</p>
		<%#= t.attrs.to_json %>
		<br>
		<p>Text</p>
		<%#= t.attrs[:text] %>
		<br>
		<p>Hashtag Text</p>
		<%# t.attrs[:entities][:hashtags].each do |hash|%>
			<span class="singleHash"><%#= hash[:text] %></span>
		<%# end %>
		<br>
	 -->
	<%# end %>
	
		<!-- <p>Name</p> -->
		<%#= t.name %>
		<!-- <br> -->
		<!-- <p>User's Image</p> -->
		<!-- <img src="<%#= t.attrs.profile_background_image_url %>"> -->
</div> <!-- End div #hasherWrapper -->

app/views/users/index.html.erb
<div id="landerWrapper">
	<% if notice %>
	  <p class="notice"><%= notice %></p>
	<% end %>
	<h1>What's #twendn</h1>



	<% if current_user %>
	  	<div class="hash">
			<%= form_tag ({controller: "users", action: "hasher"}), method: :get do %>
			  <%= text_field_tag(:search_term, '#', {autofocus: true}) %><br />
			  <%= submit_tag("Check Hashtag") %>
			<% end %>
		</div>
	<% else %>
		<%= link_to 'Sign In With Twitter', '/auth/twitter', class: 'signin' %>  
	<% end %>

	
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/poster.html.erb
<h2>You just posted that as a tweet!</h2>
<p><%= @text %></p>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>