config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get 'users/poster', to: 'users#poster', as: 'poster'
  get 'users/hasher', to: 'users#hasher', as: 'hasher'
  post 'users/reply_to', to: 'users#reply_to', as: 'reply'
  get 'users/retweet', to: 'users#retweet', as: 'retweet'
  get 'users/unretweet', to: 'users#unretweet', as: 'unretweet'
  get 'users/favorite', to: 'users#favorite', as: 'favorite'
  get 'users/unfavorite', to: 'users#unfavorite', as: 'unfavorite'
  get 'users/follow', to: 'users#follow', as: 'follow'
  get 'users/unfollow', to: 'users#unfollow', as: 'unfollow'
  get 'stop', to: 'users#stop', as: 'stop'

  get 'us', to: 'data#us', as: 'us'
  get 'tweetdata', to: 'data#tweet_data', as: 'tweetdata'
  get 'geographytweets', to: 'data#geography_tweets', as: 'geographytweets'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/controllers/data_controller.rb
class DataController < ApplicationController
  before_action :set_datum, only: [:show, :edit, :update, :destroy]
  before_action :read_us, only: [:us]
  
  # Vector json for us map data
  def us
    render :json => @@us_data
  end

  def geography_tweets
    tweetjson = []
    @tweets = Tweet.all

    # Build object with specific properties for json d3 consumption
    @tweets.each do |t|
      unless t.coordinates.nil?
        obj = {}
        obj['type'] = "Feature"
        obj['id'] = t.id
        obj['geometry'] = t.coordinates
        obj['properties'] = t.text
        tweetjson << obj
      end
    end
      # Wraps json with equivalent of header information
      @geographyjson = {type:"FeatureCollection",features: tweetjson }
      render :json => @geographyjson
  end

  def tweet_data
    tweetjson = []
    @tweets = Tweet.all
    
    # Build object with specific properties for json d3 consumption
    @tweets.each do |t|
      obj = {}
      obj['type'] = "Feature"
      obj['id'] = t.id
      obj['geometry'] = t.coordinates
      obj['properties'] = t.text
      tweetjson << obj
    end
    # Wraps json with equivalent of header information
    @completejson = {type:"FeatureCollection",features: tweetjson }

    render :json => @completejson
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datum
      @datum = Datum.find(params[:id])
    end

    def read_us
      @@us_data = File.read("app/assets/us.json")
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datum_params
      params[:datum]
    end
end

app/views/data/index.html.erb
<h1>Listing data</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data.each do |datum| %>
      <tr>
        <td><%= link_to 'Show', datum %></td>
        <td><%= link_to 'Edit', edit_datum_path(datum) %></td>
        <td><%= link_to 'Destroy', datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Datum', new_datum_path %>

app/views/data/new.html.erb
<h1>New datum</h1>

<%= render 'form' %>

<%= link_to 'Back', data_path %>

app/views/data/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_datum_path(@datum) %> |
<%= link_to 'Back', data_path %>